### ISSUE TITLE
`graphql prepare` doesn't handle non-existent .graphqlconfig gracefully

### ISSUE THREAD

**Issue by timsuchanek** [graphql-cli/graphql-cli#100]
As we're now using the `graphql prepare` command as a hook after the deploy command in the `graphcool` cli, it would be great to handle a non-existent `.graphqlconfig` more gracefully:
![image](https://user-images.githubusercontent.com/1094804/34515233-6d98086a-f071-11e7-979e-cfbfaa0ef5a0.png)
In other words, I would just omit any terminal output of the command, when there is no `.graphqlconfig`.

Ping @kbrandwijk

**Comment by schickling** [comment]
This should directly be handled in the `graphcool-cli`. I suggest to just not invoke `graphql prepare` in the first place when there is now `.graphqlconfig` file.
