### ISSUE TITLE
create: not all boilerplates are listed

### ISSUE THREAD

**Issue by marktani** [graphql-cli/graphql-cli#106]
![image](https://user-images.githubusercontent.com/1780597/34534500-a07c64c2-f0be-11e7-9fd9-34e84e8140c8.png)

**Comment by kbrandwijk** [comment]
@marktani Which ones are missing? Because a few of them are marked as 'currently broken' in the boilerplates file. Could you submit a PR with the ones that are working now? Thanks!
https://github.com/graphql-cli/graphql-cli/blob/master/src/cmds/create/boilerplates.ts

**Comment by marktani** [comment]
Ah thanks, those marked as "currently broken" are the one I was missing 🙂
