### ISSUE TITLE
get-schema to STDOUT

### ISSUE THREAD

**Issue by felixfbecker** [graphql-cli/graphql-cli#13]
It would be awesome to do this:
```sh
graphql get-schema --stdout --json | gql2ts > gqlschema.d.ts
```

https://www.npmjs.com/package/gql2ts#with-stdin

**Comment by schickling** [comment]
Agree! Would you be open to create a PR for this?

**Comment by felixfbecker** [comment]
Was this closed by mistake?

I solved my use case with https://github.com/graphcool/get-graphql-schema, but having the multiple configured endpoints of graphql-cli would be nice

**Comment by schickling** [comment]
Sorry, yes this was closed by mistake. We'll definitely keep this on the roadmap!
