### ISSUE TITLE
graphql playground does not work

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-cli/graphql-cli#140]
`WARNING: You didn't provide an endpoint and don't have a .graphqlconfig. Make sure you have at least one of them.`

The .graphqlconfig.yml file is present, and contains a project with the graphcool extension.

**Comment by kbrandwijk** [comment]
It also shows me the eery message:

```
Error: Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.
```

**Comment by timsuchanek** [comment]
I tried to reproduce it with the latest `graphql-cli`, but couldn't.
Can you provide more information, how the `.graphqlconfig.yml` and `graphcool.yml` looks like?
Thanks!
