### ISSUE TITLE
Extend `get-graphql-schema` with options to directly download from endpoint and specify JSON or SDL as format

### ISSUE THREAD

**Issue by nikolasburk** [graphql-cli/graphql-cli#16]
I think it should be possible to use `graphql get-graphql-schema` to directly download a schema from an endpoint. It would also be nice if I could specify which format to use.

Something like the following:

```sh
graphql get-graphql-schema --endpoint URL --format FORMAT
```

**Comment by schickling** [comment]
Thanks for bringing this up @nikolasburk. This is what the [get-graphql-schema](https://github.com/graphcool/get-graphql-schema) repository is meant for. What's the specific workflow you're thinking about that's currently not supported?

**Comment by michalsanger** [comment]
Get the schema as JSON would be great

**Comment by MartinDawson** [comment]
@schickling This is really confusing. Why does get-schema package have more functionality than this package but this package? Why not just allow us to specify all the commands when using this package.

So now because I want a json graphql schema I have to uninstall this package and install the get-schema one?

**Comment by schickling** [comment]
Thanks a lot for your comment @MartinDawson. I understand your confusion/concerns and would be open to merging a PR which adds `get-graphql-schema`'s functionality. 🙂

**Comment by kbrandwijk** [comment]
JSON formatting is added in #84. I'm not sure about directly specifying an endpoint. I think an endpoint should be configured first. But I'm interested to see what @schickling thinks about that too, because it is the only reason `get-graphql-schema` will exist after #84 is merged.

**Comment by kbrandwijk** [comment]
@schickling As asked above, do you think `graphql-cli` should support directly specifying an endpoint for this command, instead of configuring it?

**Comment by schickling** [comment]
I see @kbrandwijk. If we find a good API design, I'd like that!
