### ISSUE TITLE
get-schema now gets descriptions and quotes them with triple quotes """

### ISSUE THREAD

**Issue by iki** [graphql-cli/graphql-cli#182]
All other tools like https://github.com/jimkyndemeyer/js-graphql-intellij-plugin now stopped working with the schema.

The tools mostly only support descriptions in comments `#` or string literals quoted with single/double-quotes.

Are the triple quotes part of the standard?

Can they be replaced by comments, or double quotes?

**Comment by kbrandwijk** [comment]
The triple quotes are the new standard for descriptions starting in graphql 0.12. Unfortunately, not all other (IDE) tools are up to date with 0.12, but most have either upgraded already, or have an open PR to do so.
Unfortunately, this is not something we can change, as, contrary to libraries, a CLI tool doesn't play well with peer dependencies, so 'bring your own graphql version' is not possible afaik.

**Comment by iki** [comment]
Thanks @kbrandwijk, I found the spec update https://github.com/facebook/graphql/pull/90 via https://github.com/graphql/graphql-js/releases/tag/v0.12.0.

The mentioned GraphQL Language Service used in WebStorm/IDEA plugins has open issue too https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/118, but it's first looking how to support multiple spec versions, to avoid breaking existing use.

Let's close it, in meantime we can strip descriptions manually for WebStorm:
```
sed -i "/\x22\{3\}/d" schema.graphql 
```

**Comment by RIP21** [comment]
@iki command doesn't work saying `sed: -i may not be used with stdin` on Mac OS.
Using like `sed "/\x22\{3\}/d" schema.graphql > out.graphql` shows that """ is not gone from the file. Or maybe I didn't get `sed`

**Comment by iki** [comment]
@RIP21 yes, the `-i` option is used to perform the replacement in place, ie. directly in the file provided as argument, so you can use either `sed "..." -i file` or `sed "..." file.in > file.out`.

Both expressions work for me on Windows using bash and sed from latest Git for Windows.
```
sed -i "/\x22\{3\}/d" schema.graphql
sed "/\x22\{3\}/d" schema.graphql > schema-fixed.graphql
```

I'll check on MacOS evenings. Maybe you can try removing the backslashes before `{}`, there could be differences between sed implementations :(

**Comment by whisper-bye** [comment]
@iki work incorrect with multi lines comment

**Comment by markhorgan** [comment]
The above removes the triple quotes but not the comment text. I found the following removed single and multiline triple quote comments:

`sed -i "/\x22\{3\}.*\x22\{3\}/d;/\x22\{3\}/,/\x22\{3\}/d" schema.graphql`

On MacOS you can install gnu-sed with Homebrew:

`brew install gnu-sed`

And use `gsed` instead of `sed`

**Comment by wtrocki** [comment]
This issue dated badly as """ are supported for the last couple years
