### ISSUE TITLE
Allow config through env variables

### ISSUE THREAD

**Issue by felixfbecker** [graphql-cli/graphql-cli#20]
`GRAPHQL_CONFIG_ENDPOINT_NAME` can be set, but not `GRAPHQL_CONFIG_WATCH`.
Could you just accept all config with http://yargs.js.org/docs/#api-envprefix?

**Comment by schickling** [comment]
Sounds good! Can you create a PR for this?

**Comment by kbrandwijk** [comment]
Which configuration options make sense to configure using an environment variable?
I am considering project and endpoint, but I don't know which others might make sense.

**Comment by kbrandwijk** [comment]
@schickling I like this idea overall, and I don't really care which options the user wants to set env vars for, so I'd like to go ahead with this. Can we decide on a prefix? I think `GRAPHQL_CONFIG_` would work best, because that's already partly used in `graphql-config`.

**Comment by schickling** [comment]
Sounds good @kbrandwijk!
