### ISSUE TITLE
Remove react-native/expo dependency

### ISSUE THREAD

**Issue by schickling** [graphql-cli/graphql-cli#252]
Somehow `react-native`, `expo` and other tools ended up as a dependency (introduced by @renovate-bot).

/cc @rarkins

**Comment by rarkins** [comment]
@schickling sorry, I'll take a look

**Comment by schickling** [comment]
Thanks a lot! I might be wrong, but git-blame pointed to @renovate-bot

**Comment by rarkins** [comment]
@schickling yes, it definitely looks like it was the bot. Please merge my PR https://github.com/graphql-cli/graphql-cli/pull/253 to revert the bad changes. I'll look into it in detail later

**Comment by schickling** [comment]
Very curious what the issue was 🤔
