### ISSUE TITLE
Connect --watch option with other plugin?

### ISSUE THREAD

**Issue by felixfbecker** [graphql-cli/graphql-cli#27]
`get-schema --watch` is a really awesome concept, but on it's own not very useful.
It would be awesome if codegen plugings could hook into it to regenerate code on a schema update.
Wdyt?

**Comment by schickling** [comment]
Sounds like a great idea. Could you propose a concrete design/implementation that we can discuss?

**Comment by felixfbecker** [comment]
How about this simple solution: Add a parameter `-c` that specifies a (sub)command to be run on every change (just like [chokidar-cli](https://github.com/kimmobrunfeldt/chokidar-cli)). E.g.
```
get-schema dev --watch -c codegen
```
is the equivalent of running `graphql codegen` on every update (but more efficient because the plugin is already loaded in memory etc). To pass more arguments, just put quotes around it
```
get-schema --watch -c "codegen --whatever"
```

An alternative syntax that does the same to consider would be to use `--` to separate the arguments:
```
get-schema --watch -- codegen --whatever
```

**Comment by schickling** [comment]
I like this idea. Could you create a PR?

**Comment by kbrandwijk** [comment]
Could `graphql-cli` implement a similar event system to serverless plugins? That way, even completely independent and external plugins can hook into each others events to take further action. In this case, the `codegen` plugin could hook into an event raised by `get-schema` when a new schema is available.

**Comment by schickling** [comment]
I think this is a great idea @kbrandwijk! Do you want to create a new issue with a design proposal?

**Comment by kbrandwijk** [comment]
See https://github.com/graphql-cli/graphql-cli/issues/73 for a proposal on this subject.

**Comment by kbrandwijk** [comment]
Continuing the discusson in #73
