### ISSUE TITLE
Optional Env Vars

### ISSUE THREAD

**Issue by josh** [graphql-cli/graphql-cli#271]
Given a config with multiple endpoints, graphql-cli/config attempts to eager evaluate all environment variables. In our case, we have a configuration where an environment variable is only needed for a given endpoint but an error is raised even when using the other endpoints.

For an example:

```json
{
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "development": {
        "url": "http://localhost/graphql"
      },
      "production": {
        "url": "https://example.com/graphql",
        "headers": {
          "Authorization": "Bearer ${env:API_TOKEN}",
        }
      }
    }
  }
}
```

In this case, `$API_TOKEN` is only used by the production endpoint. However, it's presence will cause `graphql get-schema` against the `development` endpoint to crash on a missing `API_TOKEN`.

A workaround is to set `API_TOKEN=junkvalue`.

This eager evaluation of environment values seems to be a recent regression. That configuration example does work as expected on graphql-cli 2.6.0.

**Comment by schickling** [comment]
Thanks a lot @josh. We're looking into it!

**Comment by josh** [comment]
@schickling thanks! I wasn't sure if the issue was graphql-cli or graphql-config. Let me know if theres anything I can do to help.

**Comment by koddsson** [comment]
As far as I can see the error will go away if we pass `throwIfUndef = false` to `resolveRef` here in `graphql-config`:

https://github.com/prismagraphql/graphql-config/blob/31d4f14b5700394772f57f19020e40db23c0f7ee/src/extensions/endpoints/resolveRefString.ts#L3

I'm not sure what the implications of this would be though, seems like the option is there for a reason.
