### ISSUE TITLE
Formatting error at end of Query on prisma.graphql?

### ISSUE THREAD

**Issue by maxdarque** [graphql-cli/graphql-cli#276]
I'm running `prisma deploy` to generate `prisma.graphql`.

```
"graphql-cli": "^2.15.9"
"prisma": "^1.6.3",
```

When I start my `graphql-yoga` server, it gives the following error:

```
Type "Node" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
```

Deep in my `prisma.graphql` file, I'm finding the code below. It looks like the comment `"""The ID of an object"""` is commenting out the rest of my `.graphql` file although it doesn't seem to impact the running of the server. Is this related? Is it a problem?

```
type Query {
  [INSERT MULTIPLE QUERIES HERE]
  """
  Fetches an object given its ID
  """
  node("""
  The ID of an object
  """
  id: ID!): Node
}

enum Region {
  NORTH_AMERICA
  EUROPE
  ASIA
  ROW
  GLOBAL
}
```

**Comment by maxdarque** [comment]
Looks like it has been fixed in `graphql-js`. See here: https://github.com/graphql/graphql-js/issues/1285

**Comment by marktani** [comment]
The warning is further discussed here: https://github.com/graphcool/prisma/issues/2225
It's unrelated to the format of the comment.
