### ISSUE TITLE
graphql-cli doesn't create folders on Windows

### ISSUE THREAD

**Issue by thetre97** [graphql-cli/graphql-cli#277]
**System:**
Windows 10
Node v9.6.1
graphql-cli v2.15.9

I installed prisma, and created a new project with `prisma init projectname`. 
It went through the first two questions, e.g. database or full boilerplate, then asked what boilerplate. I selected node-advanced. It then downloaded the boilerplate and then installed all dependencies. However, there it stops. According to the docs, it should ask where to deploy it… so I then tried manually running `prisma deploy` and it throws a couple of errors, saying --\database\prisma.yml could not be found. as well as the prisma.yml. I opened the folder, and found it has installed the boilerplate like the below image.

![capture](https://user-images.githubusercontent.com/12587127/39136437-25ed6d4a-4713-11e8-9fd1-cf00f78807bf.JPG)

I then tried `graphql create projectname --boilerplate node-advanced`, as per [this](https://www.graph.cool/forum/t/prisma-cli-v1-6-3-doesnt-create-folders/3256) suggestion. However, the same thing happens. It seems to be appending the folder name to the filename, rather than creating a directory. 

I then tried this using bash on windows, and everything worked perfectly. So I am thinking it must be a windows issue?

**Comment by marktani** [comment]
> I then tried this using bash on windows

How did you try it before if not bash?

**Comment by thetre97** [comment]
Following [this doc](https://www.prisma.io/docs/1.0/quickstart/backend/node/node-phe8vai1oo), It seems to suggest you can use Windows. So I was just using Powershell.

To clarify: when I said bash on windows, I meant Ubuntu on windows, i.e WSL.

**Comment by mauricedb** [comment]
Same issue here when I use `graphql create my-app --boilerplate react-fullstack-basic` on Windows 10. 

The same behavior when I use a standard  command shell, Powershell or a MINGW64 Bash shell.

End result:
```
$ ls my-app/
LICENSE                              server_src_index.js
node_modules/                        server_src_schema.graphql
package.json                         server_yarn.lock
public__redirects                    src_assets_close.svg
public_favicon.ico                   src_assets_plus.svg
public_index.html                    src_components_CreatePage.js
README.md                            src_components_DetailPage.js
server_.gitignore                    src_components_DraftsPage.js
server_.graphqlconfig.yml            src_components_FeedPage.js
server_database_datamodel.graphql    src_components_Post.js
server_database_prisma.yml           src_constants_modalStyle.js
server_database_seed.graphql         src_index.css
server_package.json                  src_index.js
server_src_generated_prisma.graphql  yarn.lock
```

Node: v9.8.0
graphql-cli: 2.15.11
Windows 10: 1709

**Comment by jeffshadap** [comment]
Same issue on Windows 10

**Comment by jeffshadap** [comment]
Works fine with adm-zip@0.4.7
https://github.com/cthackers/adm-zip/issues/221
https://github.com/cthackers/adm-zip/issues/220

**Comment by cktang88** [comment]
This also fixes graphql-boilerplates/node-graphql-server#302

**Comment by thetre97** [comment]
👍 

v2.15.14 works fine now, but v2.16.0-beta.6 still seems to have the same issue?
