### ISSUE TITLE
graphql get-schema -e [endpoint] -c  fails on 2.16.0

### ISSUE THREAD

**Issue by daavaa** [graphql-cli/graphql-cli#299]
running this command on 2.15.8 causes zero problem:
`graphql get-schema -o schema.graphql \
      -e http://localhost:3001/graphql\?clientId\=xxxxxxxxxx
`

but with new 2.16.0 installed i'm getting following error
`Implications failed:
 all -> --no-output all -> --no-endpoint`

I can see flag `--console` working since one error then gone, but still seems like you do not parse `-e, --endpoint, -o, --output` args.

Please advise,
kind regards

**Comment by jvbianchi** [comment]
I have the same problem

**Comment by bradzacher** [comment]
the workaround is to add `--no-all` to your command line.

**Comment by marktani** [comment]
Thanks for bringing this up!
We should make it work like this: `graphql get-schema --endpoint http://... --output output.graphql`.
