### ISSUE TITLE
warning command prepare both exists in plugin and is shipped with the graphql-cli

### ISSUE THREAD

**Issue by marktani** [graphql-cli/graphql-cli#326]
In many situations you are getting this warning:

> warning command prepare both exists in plugin xx/node_modules/graphql-cli-prepare and is shipped with the graphql-cli. The plugin is being ignored.

The warning should be more clear, or it should be resolved.

**Comment by JalilArfaoui** [comment]
I have the same error, I dont know why, and I cannot get any schema to be generated. Why is graphql-cli complaining about that ?

**Comment by JalilArfaoui** [comment]
After hours of try-and-error, I got rid of the error by uninstalling graphql-cli and re-installing it globally (was local). So, it was my mistake, but I was still missing a clearer message, or the ability for graphql-cli to work locally.
