### ISSUE TITLE
GraphQL 14.x.x support 

### ISSUE THREAD

**Issue by rlancer** [graphql-cli/graphql-cli#345]

**Comment by nehaleem** [comment]
Yes please! Add `graphql` as peerDependency rather as dependency.

Im using graphql `14.0.0` on the server, so with version `2.16.7` of `graphql-cli` and command `graphql-cli get-schema` i get this error:

```
Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.
```

But when ill delete `graphql` inside `graphql-cli/node_modules`, it will take my installed version `14` and its working. This should be fixed only with `peerDependency`, right?

**Comment by TimonVS** [comment]
I'm now getting this error:

```
⚠ Cannot use GraphQLSchema "[object Object]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

I suspect this happens because of an older version of `graphql` is being used, though I don't really understand why this error occurs since I installed it globally. The master branch already has been updated to `14.0.0` can this version be published on npm? Maybe using the `next` tag? :)

**Comment by checkmatez** [comment]
@schickling @maticzav Can you guys publish new version on npm with graphql 14.0.0? We have this error too.

**Comment by maticzav** [comment]
Hey @checkmatez 👋,

We had some issues with `pkg`ing of the `graphql-cli`, which I believe should be resolved now. Could you try using the latest version (`3.0.0`) and verify this is no longer an issue for you? 🙂
