### ISSUE TITLE
graphql create not working for react-fullstack-graphql?

### ISSUE THREAD

**Issue by udithv** [graphql-cli/graphql-cli#387]
Ran the following command

`graphql create my-app --boilerplate react-fullstack-advanced`

display select menu without the said project instead of downloading.

**Comment by bhayward93** [comment]
I forked this repo and added it back in manually, wasn't too much hassle.

**Comment by pankaja92** [comment]
@schickling I have latest version of graphql which is 3.0.11 .
So, I executed `graphql create my-app` . But it doesn't show the _react-fullstack-advanced_ . So, any idea how to resolve this ?
