### ISSUE TITLE
`graphql get-schema --all` to refresh schemas for all projects/endpoints

### ISSUE THREAD

**Issue by schickling** [graphql-cli/graphql-cli#54]

**Comment by kbrandwijk** [comment]
I will create a PR after the other `get-schema` related PR's are merged, to avoid conflicts.

**Comment by kbrandwijk** [comment]
Would you like the cli to process all projects if you...
1. Don't specify a project, or:
2. Explicitly specify `--all`?

**Comment by schickling** [comment]
I'd say (2)
