### ISSUE TITLE
[beta] create command doesn't work on Windows

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-cli/graphql-cli#64]
```shell
[graphql create] Installing node dependencies...

spawn yarn ENOENT
```

**Comment by schickling** [comment]
Thanks for raising this @kbrandwijk. Would be great if you could look into this and create a PR as we currently don't have a Windows machine available to test. 👌

**Comment by kbrandwijk** [comment]
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by kbrandwijk** [comment]
This seems fixed.
