### ISSUE TITLE
Add import support to cli commands

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-cli/graphql-cli#68]
Based on some discussions on `graphql-import`, would it be an idea to add a command to the cli to process imports, and generate a resulting schema, so it could become part of build npm scripts easily, without needing any loaders? If so, what should it be called?

Also, it might be good to support schemas with imports on other commands, like `lint` and maybe others.

**Comment by schickling** [comment]
I think this behaviour would be best in a separate plugin for now.

Please also note, that `graphql-config` supports `graphql-import` out of the box.

**Comment by kbrandwijk** [comment]
I'll check it out.

**Comment by kbrandwijk** [comment]
Aaaaand... here it is: https://github.com/supergraphql/graphql-cli-bundle
Any mention in the readme for published plugins?

**Comment by schickling** [comment]
Awesome! Feel free to create a PR for the readme.
