### ISSUE TITLE
eslint and webstorm complain about get-schema output

### ISSUE THREAD

**Issue by portenez** [graphql-cli/graphql-cli#70]
This happens 😿 

```gherkin
Given I have a graphql endpoint
And it serves a schema with comments/docs/descriptions
When I use graphql-cli to generate the schema (graphql get-schema -e default)
Then the output schema.graphql cannot be be parsed by eslint plugin and webstorm plugin
```

This should be happening: 🙏 

```gherkin
Given I have a graphql endpoint
And it serves a schema with comments/docs/descriptions
When I use graphql-cli to generate the schema (graphql get-schema -e default)
Then the output schema.graphql can be parsed by eslint plugin and webstorm plugin
```

From a type:

```graphql
# It's some sort of pet
type Pet {
  name: String
}
```

When generated by `get-schema` generates new syntax which cannot be parsed by eslint or webstorm plugins

```graphql
"""It's some sort of pet"""
type Pet {
  name: String
}
```
# Plugin versions:

**ESLINT** `"eslint-plugin-graphql": "^1.4.1"`
**WEBSTORM** ``JS GraphQL: 1.6.2`

**Comment by kbrandwijk** [comment]
This schema is valid according to the most recent graphql spec: https://github.com/graphql/graphql-js/releases/tag/v0.12.0.

**Comment by portenez** [comment]
Updated ticket title and provided plugin versions.

**Comment by schickling** [comment]
As @kbrandwijk mentioned, this is according to the current official GraphQL spec. The right way forward is to help eslint + webstorm to support the newest GraphQL version. Until then I recommend to use a previous version of the graphql-cli.

**Comment by portenez** [comment]
@schickling I tried reverting `graphql-cli` all the way to version 1.1.0 (`npm install -g graphql-cli@1.1.0`) and `graphql-cli` was still generating the new schema type. 

I was wondering if the `graphql` version defined in the `graphql-cli` package.json was not locked, and it always installing the newest, but I navigated to the location where `graphql-cli` is installed and checked the version of `graphql`, and it is indeed `0.11.6`.  Maybe somewhere in the modules the version is not locked?

**Comment by kbrandwijk** [comment]
Closing this for now, as it has no direct relation to `graphql-cli` (how you got the schema), but only with your tools and their compatibility with graphql 0.12.

**Comment by kikoseijo** [comment]
@portenez you did find why, got same thing, got triple comas when doing graphql get-schema

```typescript
type Mutation {
  """A mutation"""
  updateUserEmail(id: String, email: String): UpdateUserEmailPayload
}
```

and the error, 

```5:3 Syntax Error GraphQL request (5:3) Expected Name, found String  4: type Mutation { 5:   """A mutation"""      ^```

If you found why and can help, 😊

**Comment by portenez** [comment]
@kikoseijo  This is a new valid syntax introduced in gql 0.12. The problem is not so much the syntax, but the lack of support from the webstorm plugin. For eslint and other tools, I updated graphql to version 0.12 and that solves the issue.

**Comment by kikoseijo** [comment]
Thanks a lot for pointing in the right direction,  after couple hours I manage to upgrade the following:

```
"babel-plugin-relay": "^1.5.0-rc.1",
"react-relay": "^1.5.0-rc.1",
"relay-compiler": "1.5.0-rc.1",
```

This 3 must match, I can start coding, finally!!

Appreciate your help @portenez !
