### ISSUE TITLE
The project created by cli 2.1.0 beta doesn't work

### ISSUE THREAD

**Issue by state0fmind** [graphql-cli/graphql-cli#71]
`(node:938) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [ERROR] in /Users/state0fmind/Projects/GitHub/blogr/graphcool.yml: Errors while validating graphcool.yml:
  data should have required property 'stages'`

`(node:938) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by schickling** [comment]
This issue was moved to graphcool/framework#1424
