### ISSUE TITLE
graphql create should be interactive if no directory was specified

### ISSUE THREAD

**Issue by marktani** [graphql-cli/graphql-cli#72]
![pasted image at 2017_12_19 07_11 pm](https://user-images.githubusercontent.com/1780597/34201921-6526acbe-e576-11e7-8bfd-bd12ee8214b8.png)

**Comment by schickling** [comment]
Great point @marktani. This is now possible in the newest `@beta` version.

**Comment by marktani** [comment]
shoutout to @sorenbs for the idea 😄
