### ISSUE TITLE
`graphql create` failing intermittently

### ISSUE THREAD

**Issue by grahamb** [graphql-cli/graphql-cli#75]
# Issue description
When running `graphql create <directory-name>`, the command will succeed only some of the time. Otherwise, it fails with an error from node.

If I repeatedly re-run `graphql create` it will eventually succeed.

```
$ graphql create test  
? Choose GraphQL boilerplate project: node-basic              Basic GraphQL server (incl. database)
[graphql create] Downloading boilerplate from https://github.com/graphql-boilerplates/node-graphql-server/archive/master.zip...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: invalid signature: 0xa292e0fc
    at /Users/grahamb/.nvm/versions/node/v8.9.3/lib/node_modules/graphql-cli/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

```
# Versions
- graphql-cli 2.1.0
- nodejs 8.9.3
- macOS 10.12.6

![screenshot 2017-12-20 16 49 35](https://user-images.githubusercontent.com/146111/34235415-6d349ea4-e5a6-11e7-9026-13d2325ac8cd.png)

**Comment by schickling** [comment]
@kbrandwijk as you've introduced the `unzip` library, would you mind taking a look into this?
