### ISSUE TITLE
Must provide schema definition with query type or a type named Query.

### ISSUE THREAD

**Issue by mrtnzlml** [graphql-cli/graphql-cli#76]
Hi, I tried to upgrade this dependency but after running `get-schema` command I get this error:

```
Downloading introspection from https://graphql.kiwi.com/
✖ 
Must provide schema definition with query type or a type named Query.
```

It's _probably_ because we are not using root query with the name `Query` but `RootQuery` (it works if I remove the schema completely or rename `RootQuery` -> `Query`). It seems like an unfortunate change. Not sure if it's problem of this CLI but I think this was the only change I made...

Thanks for your help... :)

**Comment by schickling** [comment]
This seems to be a issue introduced with graphql-js 0.12. Maybe you can take a look there?

**Comment by mrtnzlml** [comment]
Maybe but I intentionally downgraded to the old GraphQL version with Yarn `resolutions`. I went directly here because everything else around GraphQL seems to be working...

**Comment by kbrandwijk** [comment]
I have tested this with the last version, and when I run `graphql get-schema` on your endpoint, it succeeds and the 'schema definition' is part of the output schema:
```graphql
schema {
  query: RootQuery
  mutation: RootMutation
}
```
So closing this for now. If you run into other problems, please open a new issue.
